export function handleError(data: Array<number>) {}
